# Generated by Django 2.2.12 on 2020-04-09 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'userip',
            },
        ),
    ]
